[CMOB-1302] added basic design, Fragments, RecyclerView Items, Landscape mode
ninikokra/SPACE--Chat pull request #1
Opened 2023-04-18 10:12 UTC by ninikokra

https://spaceneobank.atlassian.net/browse/CMOB-1302

2023-04-18 12:45 UTC, Gio481 commented on app/src/main/res/layout/bottom_user_item.xml
> +    android:layout_margin="14dp">
რესურშებში :დ

2023-04-18 12:45 UTC, Gio481 commented on app/src/main/res/layout/bottom_user_item.xml
> +        android:maxWidth="300dp"
რესურსებში

2023-04-18 12:46 UTC, Gio481 commented on app/src/main/res/layout/bottom_user_item.xml
> +        android:layout_height="0dp"
რესურსებში

2023-04-18 12:46 UTC, Gio481 commented on app/src/main/res/layout/fragment_bottom_user.xml
> +        android:layout_height="0dp"
რესურსებში

2023-04-18 12:47 UTC, Gio481 commented on app/src/main/res/values/strings.xml
> +    <string name="zezva_text_input">კარგად ზეზვა, შენ როგორ ხარ?</string>
წასაშლელია ეს სტრინგები

2023-04-18 12:48 UTC, Gio481 commented on app/src/main/res/values/text_style.xml
> +    <style name="text_style_medium">
სახელი ასე დაარქვი ამ სტილს, mediuamMyriadGeo_Normal, თუ ბოლდი გექნება mediumMyriadGeo_Bold

2023-04-18 12:49 UTC, bchmsl approved these changes

2023-04-18 12:49 UTC, bchmsl commented on app/src/main/res/layout-land/activity_main.xml
> +        android:background="@color/yellow_light"></View>
როდესაც შიგნით არაფერს წერ დამხურავი ტეგი ცალკე არ გჭირდება, გააერთანე

2023-04-18 12:49 UTC, bchmsl commented on app/src/main/res/layout/fragment_top_user.xml
> +    </com.google.android.material.textfield.TextInputLayout>
სტილებში გაიტანე პარამეტრები და დაუსეტე ელემენტებს, ნაკლები კოდი გექნება და კოდის გამეორებაც აღარ იქნება

2023-04-18 12:49 UTC, bchmsl commented on app/src/main/res/values/dimen.xml
> +
ამხელა დაშორებები არ გინდა

2023-04-18 12:49 UTC, Gio481 commented
@ninikokra dp და sp სადაც გაქვს შეამოწმე და ყველგან დარწმუნდი რო ჩაჰარდკოდებულს არ იყენებ და რესურსებში გაქვს გატანილი

2023-04-18 13:16 UTC, gioqemoklidze requested changes

2023-04-18 13:16 UTC, gioqemoklidze commented on app/src/main/java/com/example/space__chat/Presentation/BaseFragment.kt
> +package com.example.space__chat.Presentation
base პექიჯი გააკეთე და იქ ჩააგდე

2023-04-18 13:16 UTC, gioqemoklidze commented on app/src/main/res/layout/top_user_item.xml
> +        android:tint="@color/gray4"
ეცადე რო ციფრები არ გამოიყენო სახელებში

2023-04-18 13:16 UTC, gioqemoklidze commented on app/src/main/res/layout/top_user_item.xml
> +        android:id="@+id/zezvaSmallBubble"
აიდი შეცვალე

2023-04-18 13:16 UTC, gioqemoklidze commented on app/src/main/res/layout/top_user_item.xml
> +        android:id="@+id/zezvaBigBuuble"
აქაც

2023-04-18 13:16 UTC, gioqemoklidze commented on app/src/main/res/layout/top_user_item.xml
> +        android:id="@+id/zezvaMessageTV"
აქაც

2023-04-18 13:16 UTC, gioqemoklidze commented on app/src/main/res/layout/top_user_item.xml
> +        android:id="@+id/zezvaTimeStampTV"
აქაც

2023-04-18 13:16 UTC, gioqemoklidze commented on app/src/main/res/layout/fragment_top_user.xml
> +        app:boxStrokeWidth="1dp"
დიმენშენებში გაიტანე

2023-04-18 13:16 UTC, gioqemoklidze commented on app/src/main/res/layout/fragment_bottom_user.xml
> +        android:layout_height="0dp"
რესურსებში იმიტო გაგვაქ რო სხვადასხვა ზომის სქრინებისთვის სხვადასხვა დიმენშენ ფაილი შეიქმნას და მაგალითად dimen_5p პატარა ეკრანისთვის 5dp იყოს და დიდისთვის 10dp , 0 დპ ყველგან 0 დპა ამიტომ ამის რესურსებში გატანა არაა სავალდებულო

2023-04-18 13:16 UTC, gioqemoklidze commented on app/src/main/res/layout/bottom_user_item.xml
> +        android:layout_height="0dp"
სეიმ რაც ზევით დავწერე

2023-04-18 13:16 UTC, gioqemoklidze commented on app/src/main/res/layout/bottom_user_item.xml
> +        android:layout_height="0dp"
0 დპზე

2023-04-18 15:56 UTC, ninikokra commented on app/src/main/res/layout/fragment_top_user.xml
> +        app:boxStrokeWidth="1dp"
done

2023-04-18 15:56 UTC, ninikokra commented on app/src/main/res/layout/top_user_item.xml
> +        android:id="@+id/zezvaTimeStampTV"
done

2023-04-18 15:56 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/Presentation/BaseFragment.kt
> +package com.example.space__chat.Presentation
done

2023-04-18 15:56 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/MainActivity.kt
> +            .commit()
done

2023-04-18 15:57 UTC, ninikokra commented on app/src/main/res/values/text_style.xml
> +    <style name="text_style_medium">
done

2023-04-18 15:57 UTC, ninikokra commented on app/src/main/res/values/strings.xml
> +    <string name="zezva_text_input">კარგად ზეზვა, შენ როგორ ხარ?</string>
done

2023-04-18 15:57 UTC, ninikokra commented on app/src/main/res/layout/fragment_bottom_user.xml
> +        app:boxStrokeWidth="1dp"
done

2023-04-18 15:57 UTC, ninikokra commented on app/src/main/res/layout/bottom_user_item.xml
> +        android:maxWidth="300dp"
done

2023-04-18 15:57 UTC, ninikokra commented on app/src/main/res/layout/bottom_user_item.xml
> +        android:layout_height="0dp"
done

2023-04-18 16:28 UTC, bchmsl requested changes

2023-04-18 16:28 UTC, bchmsl commented on app/src/main/java/com/example/space__chat/Presentation/BASE/BaseFragment.kt
აპლიკაციის package-ებს snake-თი დაარქვი სახელები, არ გამოიყენო Capitalized სიმბოლოები

2023-04-18 16:28 UTC, bchmsl commented on app/src/main/res/layout/bottom_user_item.xml
id-ების გაწერის დროს არაა საჭირო დააკონკრეტო topUser-ია თუ bottomUser, რადგან სხვადასხვა xml ფაილებში გიწერია და binding-ს იყენებ. უბრალოდ დააწერე userMessageTV და ა.შ ორივე ფრაგმენტზე

2023-04-18 16:28 UTC, bchmsl commented on app/src/main/res/layout/bottom_user_item.xml
> +        android:id="@+id/bottomUserSmallBubble"
დააკონკრეტე აიდების დროს რა ელემენტია, კოტლინის მხრიდან როდესაც მიწვდები უფრო გაგიმარტივდება გაიგო ImageView-ა თუ სხვა ელემენტი როდესაც id გექნება მაგალითად userSmallBubbleIV და არა userSmallBubble.
top-ზე და bottom-ზე დაგიწერე ზემოთ

2023-04-18 16:28 UTC, bchmsl commented on app/src/main/res/layout/bottom_user_item.xml
>          app:layout_constraintDimensionRatio="1.1"
constraintDimensionRatio **1.1** რატომ?

2023-04-18 16:28 UTC, bchmsl commented on app/src/main/res/layout/top_user_item.xml
აიდების შესახებ რაც bottom_user_item.xml-ში დაგიწერე იგივე

2023-04-18 16:28 UTC, bchmsl commented on app/src/main/res/values/text_style.xml
> +    <style name="mediuamMyriadGeo_Normal">
სტილებს მშობლად გაუწერე მშობელი ელემენტი. ასე ყველა ელემენტის სტილებში შეგეძლება ამ სტილის დამატება, რაც, რა თქმა უნდა, არასწორია.
```suggestion
    <style name="Base.Widget.AppCompat.TextView.MessageTextView" parent="Widget.AppCompat.TextView">
```

2023-04-18 16:28 UTC, bchmsl commented on app/src/main/res/values/text_style.xml
ყურადღება მიაქციე სიტყვების სწორად წერას. (ვგულისხმობ "mediuam" მე-3 ხაზში, "Norma" მე-9 ხაზში და ა.შ.)

2023-04-18 16:28 UTC, bchmsl commented on app/src/main/res/values/dimen.xml
dp და sp ქვედა ტირეებით გამოყავი, წერის დროს უფრო გაგიმარტივდება და ასოებში არ აგერევა რიცხვები

2023-04-18 16:28 UTC, bchmsl commented on app/src/main/res/layout/fragment_top_user.xml
აიდების შესახებ რაც bottom_user_item.xml-ში დაგიწერე იგივე

2023-04-18 16:28 UTC, bchmsl commented on app/src/main/res/layout/fragment_bottom_user.xml
აიდების შესახებ რაც bottom_user_item.xml-ში დაგიწერე იგივე

2023-04-18 16:28 UTC, bchmsl commented on app/src/main/res/values/dimen.xml
გამოტოვებები ეცადე 1 ხაზზე მეტი არ გქონდეს

2023-04-19 12:33 UTC, AnaRusadze requested changes

2023-04-19 12:33 UTC, AnaRusadze commented on app/src/main/res/drawable-v24/bg_bubble.xml
> +</shape>
drawable-v24ის ფექეჯიდან drawable-ში გადაიტანე ყველაფერი

2023-04-19 12:33 UTC, AnaRusadze commented on app/src/main/res/drawable-v24/input_scroll_thumb.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
თუ აიქონია პრეფიქსად ic მიუთითე, თუ ბექგრაუნდი bkg, თუ შეიპი - shape და ასე შემდეგ

2023-04-19 12:33 UTC, AnaRusadze commented on app/src/main/res/layout-land/activity_main.xml
> +    android:id="@+id/activityMainLLayout"
activityMainLLayout ზედმეტი ლ

2023-04-19 12:33 UTC, AnaRusadze commented on app/src/main/res/layout/activity_main.xml
> -</androidx.constraintlayout.widget.ConstraintLayout>
ქონსთრეინთის გამოყენება რატომ გადაიფიქრე?

2023-04-19 12:33 UTC, AnaRusadze commented on app/src/main/res/layout/bottom_user_item.xml
> +    android:layout_gravity="bottom|end"
ქონსთრეინთს არ სჭირდება გრევითის მითითება

2023-04-19 12:33 UTC, AnaRusadze commented on app/src/main/res/layout/bottom_user_item.xml
> +    android:layout_gravity="bottom|end"
კოდი დააფორმატირე, რომ რიგითობა დალაგდეს сtrl +alt + l

2023-04-19 12:33 UTC, AnaRusadze commented on app/src/main/res/layout/bottom_user_item.xml
> +        android:textColor="@color/black_light"
"@color/black_light" ფერის სახელი ცოტა გაუგებარია, წინააღმდეგობაში მოდის black და light

2023-04-19 12:33 UTC, AnaRusadze commented on app/src/main/res/values/dimen.xml
> +
და ზრდადობის მიზედვით დაალაგე, უფრო კომფორტულია

2023-04-19 13:02 UTC, ninikokra commented on app/src/main/res/drawable-v24/bg_bubble.xml
> +</shape>
done

2023-04-19 13:03 UTC, ninikokra commented on app/src/main/res/layout/bottom_user_item.xml
> +        android:textColor="@color/black_light"
done

2023-04-20 07:32 UTC, AnaRusadze requested changes
gitignore ფაილში  მიამატე ".idea/" რომ პრში ამ გაფართოებების ფაილები არ გამოჩნდეს

2023-04-20 08:14 UTC, ninikokra commented on app/src/main/res/drawable/send_button.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Done

2023-04-20 08:32 UTC, gioqemoklidze requested changes

2023-04-20 08:32 UTC, gioqemoklidze commented on app/src/main/java/com/example/space__chat/Presentation/BASE/BaseFragment.kt
> +package com.example.space__chat.Presentation.BASE
ფექიჯის სახელი პატარა ასოებით

2023-04-20 08:32 UTC, gioqemoklidze commented on app/src/main/java/com/example/space__chat/MainActivity.kt
ფრეზენთეიშენში გადააგდე

2023-04-20 08:32 UTC, gioqemoklidze commented on app/src/main/java/com/example/space__chat/Presentation/TopUserScreen/TopUserFragment.kt
> +package com.example.space__chat.Presentation.TopUserScreen
ფექიჯის სახელი  აქაც შესაცვლელია

2023-04-20 08:52 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/Presentation/TopUserScreen/TopUserFragment.kt
> +package com.example.space__chat.Presentation.TopUserScreen
done

2023-04-20 08:52 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/Presentation/BottomUserScreen/BottomUserFragment.kt
> +package com.example.space__chat.Presentation.BottomUserScreen
done

2023-04-20 08:52 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/MainActivity.kt
done

2023-04-20 09:09 UTC, iTarley commented on app/src/main/java/com/example/space__chat/presentation/bottom_user_screen/BottomUserFragment.kt
> +    private val viewModel: BottomUserViewModel by viewModels()
ვიუმოდელიც შეგიძლია გაიტანო baseFragment-ში

2023-04-20 09:09 UTC, iTarley commented on app/src/main/res/layout/activity_main.xml
> +            android:visibility="gone" />
ორი იმაგე ვიუ არ გჭირდება, გააკეთე ერთით

2023-04-20 09:09 UTC, iTarley commented on app/src/main/res/layout/activity_main.xml
> -</androidx.constraintlayout.widget.ConstraintLayout>
ისე ქონსთრეითი უფრო მძიმე ტიპი არ არის ? მე როგორც ვიცი თუ ადვილი view-ს ვაწყობთ უკეთესია Linear-ი იყოს

2023-04-20 09:14 UTC, ninikokra commented on app/src/main/res/values/dimen.xml
> +
done

2023-04-20 09:34 UTC, ninikokra commented on app/src/main/res/layout/activity_main.xml
> +            android:visibility="gone" />
done

2023-04-20 09:34 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/presentation/bottom_user_screen/BottomUserFragment.kt
> +    private val viewModel: BottomUserViewModel by viewModels()
done

2023-04-20 10:04 UTC, iTarley approved these changes

2023-04-20 10:32 UTC, gioqemoklidze requested changes

2023-04-20 10:32 UTC, gioqemoklidze commented on app/src/main/java/com/example/space__chat/presentation/base/BaseFragment.kt
> +    protected abstract val viewModel: VM
ეს ფრივეითი გახადე და ვიუმოდელის შექმნა აქეთ გადმოიტანე ბეიზ კლასში

2023-04-20 10:32 UTC, gioqemoklidze commented on app/src/main/java/com/example/space__chat/presentation/base/BaseFragment.kt
> +    protected abstract val viewModel: VM
და ონ ბაინდ ფუნქციას პარამეტრად გაატანე მერე ეს შენი ვიუმოდელი

2023-04-20 10:37 UTC, bchmsl approved these changes
აიდებთან დაკავშირებით რაღაც ხარვეზები ისევ არის, მაგრამ კარგია

2023-04-20 11:25 UTC, AnaRusadze approved these changes

2023-04-20 14:08 UTC, gioqemoklidze approved these changes

2023-04-20 14:10 UTC, AnaRusadze approved these changes

2023-04-20 14:10 UTC, merged