[CMOB-1335]Changed Fragments, background color switch, added RV Adapter, some Roo…
ninikokra/SPACE--Chat pull request #3
Opened 2023-04-25 13:28 UTC by ninikokra

https://spaceneobank.atlassian.net/browse/CMOB-1335

2023-04-26 09:41 UTC, AnaRusadze requested changes
- ბეიზ ფრაგმენტი უნდა იყოს presentation -> base ში

> chatFragment და chatViewModel უნდა იყოს შესაბამისად presentation ui და presentation vm (viewmodel) ში

> ადაპტერი უნდა იყოს ui-ში ფრაგმენტთან 
> იუზერის ენამი უტილებიდან გადმოიტანე model -ის ფექეჯში

2023-04-26 09:41 UTC, AnaRusadze commented on app/src/main/java/com/example/space__chat/presentation/MainActivity.kt
>  class MainActivity : AppCompatActivity() {
ჯობია, რომ MainActivity-ს სახელში მიუთითო ზუსტად რისი ექთივითია. მეინის სახელს არ ვტოვებთ ხოლმე აპლიკაციაში. იგივე მეინვიუმოდელსაც. და ფექეჯებშიც გაანაწილე ui -> viewmodel ში.
p.s viewmodel შეგიძლია შეამოკლო და vm დაწერო

2023-04-26 09:41 UTC, AnaRusadze commented on app/src/main/java/com/example/space__chat/presentation/MainActivity.kt
> +            }
let რატომ დაგჭირდა? ვორნინგია, რომ ბაინდინგი ნალი არ იქნება

2023-04-26 09:41 UTC, AnaRusadze commented on app/src/main/java/com/example/space__chat/presentation/MainActivity.kt
> +            }
შეგიძლია შექმნა ფუნქცია 
supportFragmentManager.beginTransaction().replace()-ისთვის და პარამეტრებად გადასცე ბაინდინგის ვიუ და იუზერის ტიპი

2023-04-26 09:41 UTC, AnaRusadze commented on app/src/main/java/com/example/space__chat/presentation/MainActivity.kt
> +        }
ხო არ ეცდები სვიჩის კომპონენტის გამოყენებას, როგორც სხვებს აქვთ? სურათებით უფრო მეტი ვიუც დაემატა და მეტი ლისენერის დადებაც მოუწია.

პ.ს ფუნქციას უნდა ერქვას არსებითი სახელი, აღწერე რას აკეთებს

2023-04-26 09:41 UTC, AnaRusadze commented on app/src/main/java/com/example/space__chat/presentation/MainActivity.kt
> +                binding.nightDaySwitcherBTN?.visibility = View.GONE
შეგიძლია ვიუს visibility-ს ექსთენშენი დაამატო

2023-04-26 09:41 UTC, AnaRusadze commented on app/src/main/java/com/example/space__chat/presentation/MainActivity.kt
> +                binding.nightDaySwitcherBTN?.visibility = View.GONE
არ არის საჭირო theme-ს შეცვლის დროს ყოველი ვიუს ქოლორი დაააფდეითო, მოძებნე სხვა გზა

2023-04-26 09:41 UTC, AnaRusadze commented on app/src/main/java/com/example/space__chat/presentation/adapter/ChatRVAdapter.kt
> +            root.scaleX = if (user.name == item.sender) -1f else 1f
სქეილების მნიშვნელობები ფრაივით კონსტან ცვლადები გახადე

2023-04-26 09:41 UTC, AnaRusadze commented on app/src/main/java/com/example/space__chat/presentation/chat_screen/ChatUsersFragment.kt
> +        binding.chatInputET.setTextColor(ContextCompat.getColor(requireContext(), colorResId))
შეგიძლია დაამატო ფერის მიღების კონტექსტის ექსთენშენი

2023-04-26 09:41 UTC, AnaRusadze commented on app/src/main/java/com/example/space__chat/presentation/utils/Tints.kt
> +}
შეგიძლია ვიუს ექსთენშენი გახადო და ორივეს ჩაანაცვლებს. ფაილს დაარქმევ ViewExtensions

2023-04-26 09:50 UTC, shioandghuladze requested changes

2023-04-26 09:50 UTC, shioandghuladze commented on app/src/main/java/com/example/space__chat/data/AppModule.kt
> +private fun chatDbProvider(context: Context): ChatDataBase {
ეცადე რომ ფუნქციებს ზმნები დაარქვა ხოლმე სახელად ამ შემთხვევაში provideChatDB chatDbProvider-ის ნაცვლად

2023-04-26 09:50 UTC, shioandghuladze commented on app/src/main/java/com/example/space__chat/data/ChatDatabase.kt
> +    exportSchema = true
ეს დეფოლტად true არის რუმის დეითაბეიზში 

https://developer.android.com/reference/androidx/room/Database#exportSchema()

2023-04-26 09:50 UTC, shioandghuladze commented on app/src/main/java/com/example/space__chat/data/MessageModel.kt
> +    @ColumnInfo(name = "sender")
ეს გვადგება ხოლმე როცა გვინდა რომ ქოლუმნის სახელი მონაცემთა ბაზაში განსხვავებული იყოს მოდელის ფილდის სახელისგან, ამ შემთხვევაში მგონი არ გჭირდება 

https://developer.android.com/reference/androidx/room/ColumnInfo#getName()

2023-04-26 09:50 UTC, shioandghuladze commented on app/src/main/java/com/example/space__chat/presentation/MainActivity.kt
> +        listeners()
ზმნაზე შეცვლალე მაგალითად setListeners()

2023-04-26 09:50 UTC, shioandghuladze commented on app/src/main/java/com/example/space__chat/presentation/MainActivity.kt
> +            binding.topUserFragment?.let {
ასეთ შემთხვევებში როცა ერთი და იგივე ცვლადზე გიწევს მრავალჯერადად წვდომა (ამ შემთხვევაში binding-ზე) შეგიძლია გამოიყენო ხოლმე with ფუნქცია, ამ შემთხვევაში with(binding)

2023-04-26 09:50 UTC, shioandghuladze commented on app/src/main/java/com/example/space__chat/presentation/MainActivity.kt
> +                    ContextCompat.getColor(
უკეთესი იქნება ეს ლოგიკა რომ სხვა ფუნქციაში გაიტანო და სვითჩის ქეისებში ის ფუნქცია გამოიძახო, კოდს დაასუფთავებს და ადვილად წასაკითხი იქნება 😄

2023-04-26 09:50 UTC, shioandghuladze commented on app/src/main/java/com/example/space__chat/presentation/adapter/ChatRVAdapter.kt
> +
ზედმეტი ხაზი დაგრჩა 😄

2023-04-26 09:50 UTC, shioandghuladze commented on app/src/main/java/com/example/space__chat/presentation/adapter/ChatRVAdapter.kt
> +
ზედმეტი ხაზი

2023-04-26 09:50 UTC, shioandghuladze commented on app/src/main/java/com/example/space__chat/presentation/chat_screen/ChatUsersFragment.kt
> +
ზედმეტი ხაზი 😄

2023-04-26 15:32 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/data/AppModule.kt
> +private fun chatDbProvider(context: Context): ChatDataBase {
done

2023-04-26 15:40 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/presentation/adapter/ChatRVAdapter.kt
> +
done

2023-04-26 15:40 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/presentation/adapter/ChatRVAdapter.kt
> +
done

2023-04-26 15:40 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/presentation/chat_screen/ChatUsersFragment.kt
> +
done

2023-04-26 18:45 UTC, Gio481 requested changes

2023-04-26 18:45 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/presentation/MainScreenActivity.kt
> +
if else რო არ წერო პირდაპირ რილფეისი რო გააკეთო არა ?

2023-04-26 18:45 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/presentation/model/UserTypeEnum.kt
> +    UserReceiver
Enum აღარ უნდა ბოლოში და Sender, Receiver
UserrTypeEnum.UserSender ჯობია წასაკითხად თუ UserType.Sender 😃

2023-04-26 18:45 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/presentation/ui/ChatUsersFragment.kt
> +            initRV(this)
RV ანუ რვეული ? :დ დაარქცი initRecyclerView :დ

2023-04-26 18:45 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/presentation/ui/adapter/ChatRVAdapter.kt
> +    }
ცალკე კლასად გაიტანე

2023-04-26 18:45 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/presentation/ui/adapter/ChatRVAdapter.kt
> +            timeStampTV.scaleX = root.scaleX
layoutDirection ნახე აბა სქეილების მაგივრად

2023-04-26 18:45 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/data/MessageModel.kt
> +    val timeStamp: String?
დრო ლონგად შეინახე და როგორც გინდა ისე დააფორმატირებ

2023-04-26 18:45 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/data/MessageModel.kt
> +package com.example.space__chat.data
data ში ჩასვი model და იქ გადაიტანე ეს მოდელ კლასი

2023-04-26 18:45 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/data/AppModule.kt
> +private fun provideDao(db: ChatDataBase) = db.chatDao()
ეს დათაბეიზის მოდული ხოა და შესაბამისად სახელიც გადაარქვი ფაილს და di მოდული გააკეთე და მანდ ჩაყარე ასეთი ფაილები

2023-04-26 18:45 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/presentation/ui/adapter/ChatRVAdapter.kt
> +            root.scaleX = if (user.name == item.sender) NEGATIVE else POSITIVE
ვიუ ჰოლდერის კლასი ბოლოში იწერება

2023-04-26 18:45 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/presentation/ui/adapter/ChatRVAdapter.kt
> +    }
კომპანიონ ობჯექტი ყველაზე ბოლოში :დ

2023-04-26 18:45 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/utils/DateExtension.kt
> +}
ლონგის ექსთენშენი გააკეთე ეს და ადაპტერში გამოიყენებ დროის ტექსტვიუზე ჩასაწერად

2023-04-26 18:46 UTC, Gio481 commented
@ninikokra აიდებს ნუ არქმევ Btn, TV, დაარქვი სრულყოფილი სახელები

2023-04-26 21:42 UTC, Gio481 requested changes

2023-04-26 21:42 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/presentation/ui/adapter/ChatRVAdapter.kt
> +            timeStampTV.layoutDirection = root.layoutDirection
მარტო რუთს რო დაუწერო დანარჩენებ აღარ დასჭირდება

2023-04-26 21:42 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/utils/DiffUtil.kt
> +}
ჯენერიქი უნდა გახადო ეს და areItemsTheSame ამაზე ასე შეგიძლია oldItem === newItem

2023-04-26 21:42 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/data/Entity.kt
> +data class Entity(
ChatEntity, მარა ესეც გაქვს და MessageModel და რომელიმე ზედმეტია თუ

2023-04-26 21:50 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/presentation/ui/adapter/ChatRVAdapter.kt
> +            timeStampTV.layoutDirection = root.layoutDirection
done

2023-04-26 21:50 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/utils/DiffUtil.kt
> +}
done

2023-04-26 21:52 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/data/Entity.kt
> +data class Entity(
Message model - model classად მაქვს და Entity ენთითად:დ ამის კითხვა მეც მინდოდა)) რომელია სწორი, ერთ კლასში გაწერა თუ ცალცალკე

2023-04-27 12:37 UTC, AnaRusadze commented on app/src/main/java/com/example/space__chat/presentation/MainScreenActivity.kt
> +class MainScreenActivity : AppCompatActivity() {
სახელი შეცვალე

2023-04-27 12:37 UTC, AnaRusadze commented on app/src/main/java/com/example/space__chat/presentation/MainScreenActivity.kt
> +    private fun switchListener() {
set ან init სვიჩ ლისენერი ჯობია. ყოველთვის შეეცადე ფუნქციას ზმნის სახელი დაარქვა, ამ შემთხვევაში switch არსებითი სახელია

2023-04-27 12:37 UTC, AnaRusadze commented on app/src/main/java/com/example/space__chat/presentation/MainScreenActivity.kt
> +    private fun switchTheme(isNightModeOn: Boolean) {
ისარგებლე ენამით, ბულიანის პარამეტრი ჩაანაცვლე

2023-04-27 12:37 UTC, AnaRusadze commented on app/src/main/res/drawable/ic_switch_dark_bckg.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
ან აიქონია ან ბექგრაუნდი. სახელში ერთი უნდა იყოს და პრეფიქსად დაუწერე.  თუ ბექგრაუნდია bkg-თი შეამოკლე

2023-04-27 12:37 UTC, AnaRusadze commented on app/src/main/res/drawable/ic_switch_light_bckg.xml
> +<?xml version="1.0" encoding="utf-8"?>
ან აიქონია ან ბექგრაუნდი. სახელში ერთი უნდა იყოს და პრეფიქსად დაუწერე. თუ ბექგრაუნდია bkg-თი შეამოკლე

2023-04-27 13:52 UTC, bchmsl requested changes

2023-04-27 13:52 UTC, bchmsl commented on app/src/main/java/com/example/space__chat/presentation/model/UserType.kt
> +    Receiver
იდეურად არასწორი სახელებია, რადგან ორივე იუზერია გამგზავნიც და მიმღებიც

2023-04-27 13:52 UTC, bchmsl commented on app/src/main/java/com/example/space__chat/presentation/ui/ChatUsersFragment.kt
> +        ChatRVAdapter(UserType.valueOf(tag!!))
ეცადე non-null type არ გამოიყენო, better safe than sorry. შეამოწმე ტაგი და თუ null-ის ტოლი არაა შემდეგ გაატანე ან უბრალოდ .toString() გამოიყენე

2023-04-27 13:52 UTC, bchmsl commented on app/src/main/java/com/example/space__chat/utils/DateExtension.kt
ექსთენშენებისთვის ზედა დონეზე ცალკე ფექიჯი გააკეთე common-ში
`com/example/space__chat/common/extensions`
და აქ ჩააგდე ექსთენშენები

2023-04-27 14:35 UTC, ninikokra commented on app/src/main/res/drawable/ic_switch_light_bckg.xml
> +<?xml version="1.0" encoding="utf-8"?>
done

2023-04-27 14:35 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/presentation/MainScreenActivity.kt
> +    private fun switchTheme(isNightModeOn: Boolean) {
done

2023-04-27 14:36 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/presentation/MainScreenActivity.kt
> +class MainScreenActivity : AppCompatActivity() {
done

2023-04-27 14:36 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/presentation/ui/ChatUsersFragment.kt
> +        binding.chatFragmentRV.adapter = adapter
მესიჯებისთვის, შემდეგ ბრენჩზე რასაც გავუშვებ წესით იქ დამჭირდება, თუ არადა წავშლი. <3

2023-04-27 14:37 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/presentation/model/UserType.kt
> +    Receiver
დონე

2023-04-27 14:37 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/presentation/model/UserType.kt
> +    Receiver
done :D

2023-04-27 14:37 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/presentation/ui/ChatUsersFragment.kt
> +        ChatRVAdapter(UserType.valueOf(tag!!))
done

2023-04-27 14:38 UTC, ninikokra commented on app/src/main/java/com/example/space__chat/utils/DateExtension.kt
Utilში დავტოვე მაგრამ ექსთენშეის packageგავხსენი <3

2023-04-27 14:40 UTC, Gio481 approved these changes

2023-04-27 14:42 UTC, Gio481 commented on app/src/main/java/com/example/space__chat/data/Entity.kt
> +data class Entity(
ეგ დამოკიდებულია რა სტრუქტურა გაქვს გამოყენებული, სწორია რო ორივე გქონდეს და ვმში და ეგეთში Message გამოიყენო და Entity ში გადამეპო საბოლოო მესიჯის მოდელი რო ენთითი წავიდეს რუმში შესანახად

2023-04-28 06:47 UTC, bchmsl approved these changes

2023-04-28 06:49 UTC, shioandghuladze approved these changes

2023-04-28 07:12 UTC, merged