[CMOB-1362]changed package name, changed RecyclerView Adapter......
ninikokra/SPACE--Chat pull request #5
Opened 2023-05-02 21:02 UTC by ninikokra

https://spaceneobank.atlassian.net/browse/CMOB-1362

2023-05-03 08:26 UTC, shioandghuladze requested changes

2023-05-03 08:26 UTC, shioandghuladze commented on app/src/main/java/com/space/space__chat/data/entity/ChatEntity.kt
>  data class ChatEntity(
https://github.com/DavitTsiskarashvili/Space-Chat-App/pull/5
დავითის ეს ფულ რექვესთი ნახე რამდენიმე კომენტარი დავუწერე სახელებთან დაკავშირებით, აქ აღარ დავწერ რომ არ გადავტვირთო ტყუილად კომენტარები.

2023-05-03 08:26 UTC, shioandghuladze commented on app/src/main/java/com/space/space__chat/presentation/base/AdapterListener.kt
> +    fun getUserId(): String
ლამბდა ჯობს ამის მაგივრად

2023-05-03 09:23 UTC, ninikokra commented on app/src/main/java/com/space/space__chat/data/entity/ChatEntity.kt
>  data class ChatEntity(
done <3

2023-05-03 10:03 UTC, ninikokra commented on app/src/main/java/com/space/space__chat/presentation/base/AdapterListener.kt
> +    fun getUserId(): String
done

2023-05-04 10:39 UTC, Gio481 commented on app/src/main/java/com/space/space__chat/presentation/base/AdapterListener.kt
> +}
ესე ჩათვალე ინტერფეისში რო ინტერფეისი გქონდეს ეგრე გაქ იმიტო რო ლამბდა არის ერთ ფუნქციანი ინტერფეისი და ან მარტო ლამბდა გამოიყენე ან მარტო ინტერფეისი

2023-05-04 10:41 UTC, Gio481 commented on app/src/main/java/com/space/space__chat/presentation/base/BaseFragment.kt
> +    abstract fun userId(): String
აქ ზედმეტი იუზერაიდი გაქ და ოპტიმიზაცია უნდა

2023-05-04 10:41 UTC, Gio481 commented on app/src/main/java/com/space/space__chat/presentation/ui/ChatUsersFragment.kt
> +        ChatRVAdapter(listener)
RV აღარ უნდა

2023-05-04 10:42 UTC, Gio481 commented on app/src/main/java/com/space/space__chat/presentation/ui/ChatUsersFragment.kt
>          binding.chatInputET.text?.clear()
შეგიძლია with(binding.chatInputET)

2023-05-04 10:43 UTC, Gio481 commented on app/src/main/java/com/space/space__chat/presentation/ui/ChatUsersFragment.kt
>              viewModel.showMessages().collect {
ექსთენშენი გაუკეთე რო ყოველ ჯერზე ჯერ ლაიფსაიქლის და მერე ქოლექთის დაწერა არ დაგჭირდეს

2023-05-04 10:45 UTC, Gio481 commented on app/src/main/java/com/space/space__chat/presentation/vm/ChatUsersViewModel.kt
> +    )
არ ამოწმებ თუ მესიჯი ცარიელია და ისე დააწვა გაგზავნას ? აიდი აქ თუ ნალს ანიჭებ პირდაპირვე მოდელში მიანიჭე ნალი

2023-05-04 13:03 UTC, ninikokra commented on app/src/main/java/com/space/space__chat/presentation/base/AdapterListener.kt
> +}
done

2023-05-04 13:03 UTC, ninikokra commented on app/src/main/java/com/space/space__chat/presentation/base/BaseFragment.kt
> +    abstract fun userId(): String
done

2023-05-04 13:03 UTC, ninikokra commented on app/src/main/java/com/space/space__chat/presentation/ui/ChatUsersFragment.kt
> +        ChatRVAdapter(listener)
done

2023-05-04 13:03 UTC, ninikokra commented on app/src/main/java/com/space/space__chat/presentation/ui/ChatUsersFragment.kt
>              viewModel.showMessages().collect {
done

2023-05-04 13:03 UTC, ninikokra commented on app/src/main/java/com/space/space__chat/presentation/vm/ChatUsersViewModel.kt
> +    )
done

2023-05-04 15:37 UTC, Gio481 commented on app/src/main/java/com/space/space__chat/presentation/ui/ChatUsersFragment.kt
> +        }
with(binding.chatInputET){
   viewModel.sendMessage(text.toString, tag.toString)
   text?.clear
}
ასე გამოვა ვიუმოდელს მარტო ერთხელ იყენებ და არც გინდა with ში ჩაწერა, with(რაღაცა) რო წერ ნიშნავს იმ რაღაცაში ხარ შესული და პირდაპირ მაგის ფუნქციებს და მეთოდებს ეგრევე დაწერ

2023-05-04 15:39 UTC, Gio481 commented on app/src/main/res/layout/rv_user_item.xml
> +        style="@style/message_style"
არა რატო შეუცვალე სახელი ?

2023-05-04 16:19 UTC, ninikokra commented on app/src/main/res/layout/rv_user_item.xml
> +        style="@style/message_style"
ახალი დავამატე :დ

2023-05-05 07:41 UTC, Gio481 approved these changes

2023-05-05 09:11 UTC, GiorgiMamagulashvil1 approved these changes

2023-05-05 09:12 UTC, AnaRusadze approved these changes

2023-05-05 09:13 UTC, merged